FROM rust:1.86-slim

RUN apt-get update && apt-get install -y ca-certificates pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch --locked

WORKDIR /app

ENV CARGO_HOME=/usr/local/cargo

CMD ["cargo", "watch", "-x", "run"]
